import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";

export const metadata: Metadata = {
    title: "Salon Rium Coiffure",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="parallax-background">
                <Header />
                <main className="min-h-[600px] bg-transparent">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
